language: java
jdk:
- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE mepTest;" -U postgres

deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: effective