package com.mep.database.mapper;

import com.mep.database.entity.Administrator;
import com.mep.database.entity.AdministratorExample.Criteria;
import com.mep.database.entity.AdministratorExample.Criterion;
import com.mep.database.entity.AdministratorExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class AdministratorSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String countByExample(AdministratorExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("\"administrator\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String deleteByExample(AdministratorExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("\"administrator\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String insertSelective(Administrator record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("\"administrator\"");
        
        if (record.getAdminId() != null) {
            sql.VALUES("\"admin_id\"", "#{adminId,jdbcType=INTEGER}");
        }
        
        if (record.getAdminName() != null) {
            sql.VALUES("\"admin_name\"", "#{adminName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminEmail() != null) {
            sql.VALUES("\"admin_email\"", "#{adminEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminPassword() != null) {
            sql.VALUES("\"admin_password\"", "#{adminPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.VALUES("\"created_date\"", "#{createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.VALUES("\"updated_date\"", "#{updatedDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAdminImageUrl() != null) {
            sql.VALUES("\"admin_image_url\"", "#{adminImageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getAboutAdmin() != null) {
            sql.VALUES("\"about_admin\"", "#{aboutAdmin,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String selectByExample(AdministratorExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("\"admin_id\"");
        } else {
            sql.SELECT("\"admin_id\"");
        }
        sql.SELECT("\"admin_name\"");
        sql.SELECT("\"admin_email\"");
        sql.SELECT("\"admin_password\"");
        sql.SELECT("\"created_date\"");
        sql.SELECT("\"updated_date\"");
        sql.SELECT("\"admin_image_url\"");
        sql.SELECT("\"about_admin\"");
        sql.FROM("\"administrator\"");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Administrator record = (Administrator) parameter.get("record");
        AdministratorExample example = (AdministratorExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("\"administrator\"");
        
        if (record.getAdminId() != null) {
            sql.SET("\"admin_id\" = #{record.adminId,jdbcType=INTEGER}");
        }
        
        if (record.getAdminName() != null) {
            sql.SET("\"admin_name\" = #{record.adminName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminEmail() != null) {
            sql.SET("\"admin_email\" = #{record.adminEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminPassword() != null) {
            sql.SET("\"admin_password\" = #{record.adminPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{record.createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAdminImageUrl() != null) {
            sql.SET("\"admin_image_url\" = #{record.adminImageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getAboutAdmin() != null) {
            sql.SET("\"about_admin\" = #{record.aboutAdmin,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("\"administrator\"");
        
        sql.SET("\"admin_id\" = #{record.adminId,jdbcType=INTEGER}");
        sql.SET("\"admin_name\" = #{record.adminName,jdbcType=VARCHAR}");
        sql.SET("\"admin_email\" = #{record.adminEmail,jdbcType=VARCHAR}");
        sql.SET("\"admin_password\" = #{record.adminPassword,jdbcType=VARCHAR}");
        sql.SET("\"created_date\" = #{record.createdDate,jdbcType=TIMESTAMP}");
        sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=TIMESTAMP}");
        sql.SET("\"admin_image_url\" = #{record.adminImageUrl,jdbcType=VARCHAR}");
        sql.SET("\"about_admin\" = #{record.aboutAdmin,jdbcType=VARCHAR}");
        
        AdministratorExample example = (AdministratorExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String updateByPrimaryKeySelective(Administrator record) {
        SQL sql = new SQL();
        sql.UPDATE("\"administrator\"");
        
        if (record.getAdminName() != null) {
            sql.SET("\"admin_name\" = #{adminName,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminEmail() != null) {
            sql.SET("\"admin_email\" = #{adminEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getAdminPassword() != null) {
            sql.SET("\"admin_password\" = #{adminPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{updatedDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAdminImageUrl() != null) {
            sql.SET("\"admin_image_url\" = #{adminImageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getAboutAdmin() != null) {
            sql.SET("\"about_admin\" = #{aboutAdmin,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("\"admin_id\" = #{adminId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected void applyWhere(SQL sql, AdministratorExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}