package com.mep.database.mapper;

import com.mep.database.entity.Archive;
import com.mep.database.entity.ArchiveExample.Criteria;
import com.mep.database.entity.ArchiveExample.Criterion;
import com.mep.database.entity.ArchiveExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ArchiveSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String countByExample(ArchiveExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("\"archive\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String deleteByExample(ArchiveExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("\"archive\"");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String insertSelective(Archive record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("\"archive\"");
        
        if (record.getArchiveId() != null) {
            sql.VALUES("\"archive_id\"", "#{archiveId,jdbcType=INTEGER}");
        }
        
        if (record.getPostId() != null) {
            sql.VALUES("\"post_id\"", "#{postId,jdbcType=INTEGER}");
        }
        
        if (record.getYear() != null) {
            sql.VALUES("\"year\"", "#{year,jdbcType=VARCHAR}");
        }
        
        if (record.getMonth() != null) {
            sql.VALUES("\"month\"", "#{month,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.VALUES("\"created_date\"", "#{createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.VALUES("\"updated_date\"", "#{updatedDate,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String selectByExample(ArchiveExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("\"archive_id\"");
        } else {
            sql.SELECT("\"archive_id\"");
        }
        sql.SELECT("\"post_id\"");
        sql.SELECT("\"year\"");
        sql.SELECT("\"month\"");
        sql.SELECT("\"created_date\"");
        sql.SELECT("\"updated_date\"");
        sql.FROM("\"archive\"");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Archive record = (Archive) parameter.get("record");
        ArchiveExample example = (ArchiveExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("\"archive\"");
        
        if (record.getArchiveId() != null) {
            sql.SET("\"archive_id\" = #{record.archiveId,jdbcType=INTEGER}");
        }
        
        if (record.getPostId() != null) {
            sql.SET("\"post_id\" = #{record.postId,jdbcType=INTEGER}");
        }
        
        if (record.getYear() != null) {
            sql.SET("\"year\" = #{record.year,jdbcType=VARCHAR}");
        }
        
        if (record.getMonth() != null) {
            sql.SET("\"month\" = #{record.month,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{record.createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("\"archive\"");
        
        sql.SET("\"archive_id\" = #{record.archiveId,jdbcType=INTEGER}");
        sql.SET("\"post_id\" = #{record.postId,jdbcType=INTEGER}");
        sql.SET("\"year\" = #{record.year,jdbcType=VARCHAR}");
        sql.SET("\"month\" = #{record.month,jdbcType=VARCHAR}");
        sql.SET("\"created_date\" = #{record.createdDate,jdbcType=TIMESTAMP}");
        sql.SET("\"updated_date\" = #{record.updatedDate,jdbcType=TIMESTAMP}");
        
        ArchiveExample example = (ArchiveExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    public String updateByPrimaryKeySelective(Archive record) {
        SQL sql = new SQL();
        sql.UPDATE("\"archive\"");
        
        if (record.getPostId() != null) {
            sql.SET("\"post_id\" = #{postId,jdbcType=INTEGER}");
        }
        
        if (record.getYear() != null) {
            sql.SET("\"year\" = #{year,jdbcType=VARCHAR}");
        }
        
        if (record.getMonth() != null) {
            sql.SET("\"month\" = #{month,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedDate() != null) {
            sql.SET("\"created_date\" = #{createdDate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatedDate() != null) {
            sql.SET("\"updated_date\" = #{updatedDate,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("\"archive_id\" = #{archiveId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table archive
     *
     * @mbg.generated Sun Jul 16 17:56:51 MMT 2017
     */
    protected void applyWhere(SQL sql, ArchiveExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}