package com.mep.database.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

import com.mep.database.entity.Post;
import com.mep.database.entity.PostExample;

@Mapper
public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @SelectProvider(type=PostSqlProvider.class, method="countByExample")
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @DeleteProvider(type=PostSqlProvider.class, method="deleteByExample")
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @Delete({
        "delete from \"post\"",
        "where \"post_id\" = #{postId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @Insert({
        "insert into \"post\" (\"post_id\", \"admin_id\", ",
        "\"category_id\", \"post_title_eng\", ",
        "\"post_title_mmr\", \"post_title_img_url\", ",
        "\"post_content\", \"created_date\", ",
        "\"updated_date\", \"content_type\")",
        "values (#{postId,jdbcType=INTEGER}, #{adminId,jdbcType=INTEGER}, ",
        "#{categoryId,jdbcType=INTEGER}, #{postTitleEng,jdbcType=VARCHAR}, ",
        "#{postTitleMmr,jdbcType=VARCHAR}, #{postTitleImgUrl,jdbcType=VARCHAR}, ",
        "#{postContent,jdbcType=VARCHAR}, #{createdDate,jdbcType=TIMESTAMP}, ",
        "#{updatedDate,jdbcType=TIMESTAMP}, #{contentType,jdbcType=INTEGER})"
    })
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @InsertProvider(type=PostSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys = true, keyProperty = "postId", keyColumn="post_id")
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @SelectProvider(type=PostSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="post_id", property="postId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="post_title_eng", property="postTitleEng", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_mmr", property="postTitleMmr", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_img_url", property="postTitleImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_content", property="postContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content_type", property="contentType", jdbcType=JdbcType.INTEGER)
    })
    List<Post> selectByExampleWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @SelectProvider(type=PostSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="post_id", property="postId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="post_title_eng", property="postTitleEng", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_mmr", property="postTitleMmr", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_img_url", property="postTitleImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_content", property="postContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content_type", property="contentType", jdbcType=JdbcType.INTEGER)
    })
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @Select({
        "select",
        "\"post_id\", \"admin_id\", \"category_id\", \"post_title_eng\", \"post_title_mmr\", ",
        "\"post_title_img_url\", \"post_content\", \"created_date\", \"updated_date\", ",
        "\"content_type\"",
        "from \"post\"",
        "where \"post_id\" = #{postId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="post_id", property="postId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="admin_id", property="adminId", jdbcType=JdbcType.INTEGER),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.INTEGER),
        @Result(column="post_title_eng", property="postTitleEng", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_mmr", property="postTitleMmr", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_title_img_url", property="postTitleImgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_content", property="postContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="created_date", property="createdDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updated_date", property="updatedDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content_type", property="contentType", jdbcType=JdbcType.INTEGER)
    })
    Post selectByPrimaryKey(Integer postId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @Update({
        "update \"post\"",
        "set \"admin_id\" = #{adminId,jdbcType=INTEGER},",
          "\"category_id\" = #{categoryId,jdbcType=INTEGER},",
          "\"post_title_eng\" = #{postTitleEng,jdbcType=VARCHAR},",
          "\"post_title_mmr\" = #{postTitleMmr,jdbcType=VARCHAR},",
          "\"post_title_img_url\" = #{postTitleImgUrl,jdbcType=VARCHAR},",
          "\"post_content\" = #{postContent,jdbcType=VARCHAR},",
          "\"created_date\" = #{createdDate,jdbcType=TIMESTAMP},",
          "\"updated_date\" = #{updatedDate,jdbcType=TIMESTAMP},",
          "\"content_type\" = #{contentType,jdbcType=INTEGER}",
        "where \"post_id\" = #{postId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Post record);
}