package com.mep.database.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdministratorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public AdministratorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("\"admin_id\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("\"admin_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("\"admin_id\" =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("\"admin_id\" <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("\"admin_id\" >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"admin_id\" >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("\"admin_id\" <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"admin_id\" <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("\"admin_id\" in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("\"admin_id\" not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("\"admin_id\" between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"admin_id\" not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNull() {
            addCriterion("\"admin_name\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminNameIsNotNull() {
            addCriterion("\"admin_name\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminNameEqualTo(String value) {
            addCriterion("\"admin_name\" =", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotEqualTo(String value) {
            addCriterion("\"admin_name\" <>", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThan(String value) {
            addCriterion("\"admin_name\" >", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"admin_name\" >=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThan(String value) {
            addCriterion("\"admin_name\" <", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLessThanOrEqualTo(String value) {
            addCriterion("\"admin_name\" <=", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameLike(String value) {
            addCriterion("\"admin_name\" like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotLike(String value) {
            addCriterion("\"admin_name\" not like", value, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameIn(List<String> values) {
            addCriterion("\"admin_name\" in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotIn(List<String> values) {
            addCriterion("\"admin_name\" not in", values, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameBetween(String value1, String value2) {
            addCriterion("\"admin_name\" between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminNameNotBetween(String value1, String value2) {
            addCriterion("\"admin_name\" not between", value1, value2, "adminName");
            return (Criteria) this;
        }

        public Criteria andAdminEmailIsNull() {
            addCriterion("\"admin_email\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminEmailIsNotNull() {
            addCriterion("\"admin_email\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEmailEqualTo(String value) {
            addCriterion("\"admin_email\" =", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailNotEqualTo(String value) {
            addCriterion("\"admin_email\" <>", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailGreaterThan(String value) {
            addCriterion("\"admin_email\" >", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailGreaterThanOrEqualTo(String value) {
            addCriterion("\"admin_email\" >=", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailLessThan(String value) {
            addCriterion("\"admin_email\" <", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailLessThanOrEqualTo(String value) {
            addCriterion("\"admin_email\" <=", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailLike(String value) {
            addCriterion("\"admin_email\" like", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailNotLike(String value) {
            addCriterion("\"admin_email\" not like", value, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailIn(List<String> values) {
            addCriterion("\"admin_email\" in", values, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailNotIn(List<String> values) {
            addCriterion("\"admin_email\" not in", values, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailBetween(String value1, String value2) {
            addCriterion("\"admin_email\" between", value1, value2, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminEmailNotBetween(String value1, String value2) {
            addCriterion("\"admin_email\" not between", value1, value2, "adminEmail");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNull() {
            addCriterion("\"admin_password\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIsNotNull() {
            addCriterion("\"admin_password\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordEqualTo(String value) {
            addCriterion("\"admin_password\" =", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotEqualTo(String value) {
            addCriterion("\"admin_password\" <>", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThan(String value) {
            addCriterion("\"admin_password\" >", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("\"admin_password\" >=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThan(String value) {
            addCriterion("\"admin_password\" <", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLessThanOrEqualTo(String value) {
            addCriterion("\"admin_password\" <=", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordLike(String value) {
            addCriterion("\"admin_password\" like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotLike(String value) {
            addCriterion("\"admin_password\" not like", value, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordIn(List<String> values) {
            addCriterion("\"admin_password\" in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotIn(List<String> values) {
            addCriterion("\"admin_password\" not in", values, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordBetween(String value1, String value2) {
            addCriterion("\"admin_password\" between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andAdminPasswordNotBetween(String value1, String value2) {
            addCriterion("\"admin_password\" not between", value1, value2, "adminPassword");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("\"created_date\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("\"created_date\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("\"created_date\" =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("\"created_date\" <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("\"created_date\" >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"created_date\" >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("\"created_date\" <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("\"created_date\" <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("\"created_date\" in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("\"created_date\" not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("\"created_date\" between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("\"created_date\" not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("\"updated_date\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("\"updated_date\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("\"updated_date\" =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("\"updated_date\" <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("\"updated_date\" >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"updated_date\" >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("\"updated_date\" <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("\"updated_date\" <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("\"updated_date\" in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("\"updated_date\" not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("\"updated_date\" between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("\"updated_date\" not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlIsNull() {
            addCriterion("\"admin_image_url\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlIsNotNull() {
            addCriterion("\"admin_image_url\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlEqualTo(String value) {
            addCriterion("\"admin_image_url\" =", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlNotEqualTo(String value) {
            addCriterion("\"admin_image_url\" <>", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlGreaterThan(String value) {
            addCriterion("\"admin_image_url\" >", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("\"admin_image_url\" >=", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlLessThan(String value) {
            addCriterion("\"admin_image_url\" <", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlLessThanOrEqualTo(String value) {
            addCriterion("\"admin_image_url\" <=", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlLike(String value) {
            addCriterion("\"admin_image_url\" like", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlNotLike(String value) {
            addCriterion("\"admin_image_url\" not like", value, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlIn(List<String> values) {
            addCriterion("\"admin_image_url\" in", values, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlNotIn(List<String> values) {
            addCriterion("\"admin_image_url\" not in", values, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlBetween(String value1, String value2) {
            addCriterion("\"admin_image_url\" between", value1, value2, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAdminImageUrlNotBetween(String value1, String value2) {
            addCriterion("\"admin_image_url\" not between", value1, value2, "adminImageUrl");
            return (Criteria) this;
        }

        public Criteria andAboutAdminIsNull() {
            addCriterion("\"about_admin\" is null");
            return (Criteria) this;
        }

        public Criteria andAboutAdminIsNotNull() {
            addCriterion("\"about_admin\" is not null");
            return (Criteria) this;
        }

        public Criteria andAboutAdminEqualTo(String value) {
            addCriterion("\"about_admin\" =", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminNotEqualTo(String value) {
            addCriterion("\"about_admin\" <>", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminGreaterThan(String value) {
            addCriterion("\"about_admin\" >", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminGreaterThanOrEqualTo(String value) {
            addCriterion("\"about_admin\" >=", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminLessThan(String value) {
            addCriterion("\"about_admin\" <", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminLessThanOrEqualTo(String value) {
            addCriterion("\"about_admin\" <=", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminLike(String value) {
            addCriterion("\"about_admin\" like", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminNotLike(String value) {
            addCriterion("\"about_admin\" not like", value, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminIn(List<String> values) {
            addCriterion("\"about_admin\" in", values, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminNotIn(List<String> values) {
            addCriterion("\"about_admin\" not in", values, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminBetween(String value1, String value2) {
            addCriterion("\"about_admin\" between", value1, value2, "aboutAdmin");
            return (Criteria) this;
        }

        public Criteria andAboutAdminNotBetween(String value1, String value2) {
            addCriterion("\"about_admin\" not between", value1, value2, "aboutAdmin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table administrator
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 03 16:03:31 MMT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table administrator
     *
     * @mbg.generated Thu Aug 03 16:03:31 MMT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}