package com.mep.database.entity;

import java.io.Serializable;
import java.util.Date;

public class Post implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.admin_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.category_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_title_eng
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private String postTitleEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_title_mmr
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private String postTitleMmr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_title_img_url
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private String postTitleImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_content
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private String postContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.created_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.updated_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content_type
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private Integer contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_id
     *
     * @return the value of post.post_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_id
     *
     * @param postId the value for post.post_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.admin_id
     *
     * @return the value of post.admin_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.admin_id
     *
     * @param adminId the value for post.admin_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.category_id
     *
     * @return the value of post.category_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.category_id
     *
     * @param categoryId the value for post.category_id
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_title_eng
     *
     * @return the value of post.post_title_eng
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public String getPostTitleEng() {
        return postTitleEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_title_eng
     *
     * @param postTitleEng the value for post.post_title_eng
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setPostTitleEng(String postTitleEng) {
        this.postTitleEng = postTitleEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_title_mmr
     *
     * @return the value of post.post_title_mmr
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public String getPostTitleMmr() {
        return postTitleMmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_title_mmr
     *
     * @param postTitleMmr the value for post.post_title_mmr
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setPostTitleMmr(String postTitleMmr) {
        this.postTitleMmr = postTitleMmr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_title_img_url
     *
     * @return the value of post.post_title_img_url
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public String getPostTitleImgUrl() {
        return postTitleImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_title_img_url
     *
     * @param postTitleImgUrl the value for post.post_title_img_url
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setPostTitleImgUrl(String postTitleImgUrl) {
        this.postTitleImgUrl = postTitleImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_content
     *
     * @return the value of post.post_content
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_content
     *
     * @param postContent the value for post.post_content
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.created_date
     *
     * @return the value of post.created_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.created_date
     *
     * @param createdDate the value for post.created_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.updated_date
     *
     * @return the value of post.updated_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.updated_date
     *
     * @param updatedDate the value for post.updated_date
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content_type
     *
     * @return the value of post.content_type
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content_type
     *
     * @param contentType the value for post.content_type
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", postId=").append(postId);
        sb.append(", adminId=").append(adminId);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", postTitleEng=").append(postTitleEng);
        sb.append(", postTitleMmr=").append(postTitleMmr);
        sb.append(", postTitleImgUrl=").append(postTitleImgUrl);
        sb.append(", postContent=").append(postContent);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", contentType=").append(contentType);
        sb.append("]");
        return sb.toString();
    }
}