package com.mep.database.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public PostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPostIdIsNull() {
            addCriterion("\"post_id\" is null");
            return (Criteria) this;
        }

        public Criteria andPostIdIsNotNull() {
            addCriterion("\"post_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andPostIdEqualTo(Integer value) {
            addCriterion("\"post_id\" =", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotEqualTo(Integer value) {
            addCriterion("\"post_id\" <>", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThan(Integer value) {
            addCriterion("\"post_id\" >", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"post_id\" >=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThan(Integer value) {
            addCriterion("\"post_id\" <", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"post_id\" <=", value, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdIn(List<Integer> values) {
            addCriterion("\"post_id\" in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotIn(List<Integer> values) {
            addCriterion("\"post_id\" not in", values, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdBetween(Integer value1, Integer value2) {
            addCriterion("\"post_id\" between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andPostIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"post_id\" not between", value1, value2, "postId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNull() {
            addCriterion("\"admin_id\" is null");
            return (Criteria) this;
        }

        public Criteria andAdminIdIsNotNull() {
            addCriterion("\"admin_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andAdminIdEqualTo(Integer value) {
            addCriterion("\"admin_id\" =", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotEqualTo(Integer value) {
            addCriterion("\"admin_id\" <>", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThan(Integer value) {
            addCriterion("\"admin_id\" >", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"admin_id\" >=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThan(Integer value) {
            addCriterion("\"admin_id\" <", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"admin_id\" <=", value, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdIn(List<Integer> values) {
            addCriterion("\"admin_id\" in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotIn(List<Integer> values) {
            addCriterion("\"admin_id\" not in", values, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdBetween(Integer value1, Integer value2) {
            addCriterion("\"admin_id\" between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andAdminIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"admin_id\" not between", value1, value2, "adminId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("\"category_id\" is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("\"category_id\" is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("\"category_id\" =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("\"category_id\" <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("\"category_id\" >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"category_id\" >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("\"category_id\" <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("\"category_id\" <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("\"category_id\" in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("\"category_id\" not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("\"category_id\" between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("\"category_id\" not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngIsNull() {
            addCriterion("\"post_title_eng\" is null");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngIsNotNull() {
            addCriterion("\"post_title_eng\" is not null");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngEqualTo(String value) {
            addCriterion("\"post_title_eng\" =", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngNotEqualTo(String value) {
            addCriterion("\"post_title_eng\" <>", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngGreaterThan(String value) {
            addCriterion("\"post_title_eng\" >", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngGreaterThanOrEqualTo(String value) {
            addCriterion("\"post_title_eng\" >=", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngLessThan(String value) {
            addCriterion("\"post_title_eng\" <", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngLessThanOrEqualTo(String value) {
            addCriterion("\"post_title_eng\" <=", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngLike(String value) {
            addCriterion("\"post_title_eng\" like", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngNotLike(String value) {
            addCriterion("\"post_title_eng\" not like", value, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngIn(List<String> values) {
            addCriterion("\"post_title_eng\" in", values, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngNotIn(List<String> values) {
            addCriterion("\"post_title_eng\" not in", values, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngBetween(String value1, String value2) {
            addCriterion("\"post_title_eng\" between", value1, value2, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleEngNotBetween(String value1, String value2) {
            addCriterion("\"post_title_eng\" not between", value1, value2, "postTitleEng");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrIsNull() {
            addCriterion("\"post_title_mmr\" is null");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrIsNotNull() {
            addCriterion("\"post_title_mmr\" is not null");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrEqualTo(String value) {
            addCriterion("\"post_title_mmr\" =", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrNotEqualTo(String value) {
            addCriterion("\"post_title_mmr\" <>", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrGreaterThan(String value) {
            addCriterion("\"post_title_mmr\" >", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrGreaterThanOrEqualTo(String value) {
            addCriterion("\"post_title_mmr\" >=", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrLessThan(String value) {
            addCriterion("\"post_title_mmr\" <", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrLessThanOrEqualTo(String value) {
            addCriterion("\"post_title_mmr\" <=", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrLike(String value) {
            addCriterion("\"post_title_mmr\" like", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrNotLike(String value) {
            addCriterion("\"post_title_mmr\" not like", value, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrIn(List<String> values) {
            addCriterion("\"post_title_mmr\" in", values, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrNotIn(List<String> values) {
            addCriterion("\"post_title_mmr\" not in", values, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrBetween(String value1, String value2) {
            addCriterion("\"post_title_mmr\" between", value1, value2, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleMmrNotBetween(String value1, String value2) {
            addCriterion("\"post_title_mmr\" not between", value1, value2, "postTitleMmr");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlIsNull() {
            addCriterion("\"post_title_img_url\" is null");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlIsNotNull() {
            addCriterion("\"post_title_img_url\" is not null");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlEqualTo(String value) {
            addCriterion("\"post_title_img_url\" =", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlNotEqualTo(String value) {
            addCriterion("\"post_title_img_url\" <>", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlGreaterThan(String value) {
            addCriterion("\"post_title_img_url\" >", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("\"post_title_img_url\" >=", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlLessThan(String value) {
            addCriterion("\"post_title_img_url\" <", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlLessThanOrEqualTo(String value) {
            addCriterion("\"post_title_img_url\" <=", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlLike(String value) {
            addCriterion("\"post_title_img_url\" like", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlNotLike(String value) {
            addCriterion("\"post_title_img_url\" not like", value, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlIn(List<String> values) {
            addCriterion("\"post_title_img_url\" in", values, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlNotIn(List<String> values) {
            addCriterion("\"post_title_img_url\" not in", values, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlBetween(String value1, String value2) {
            addCriterion("\"post_title_img_url\" between", value1, value2, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostTitleImgUrlNotBetween(String value1, String value2) {
            addCriterion("\"post_title_img_url\" not between", value1, value2, "postTitleImgUrl");
            return (Criteria) this;
        }

        public Criteria andPostContentIsNull() {
            addCriterion("\"post_content\" is null");
            return (Criteria) this;
        }

        public Criteria andPostContentIsNotNull() {
            addCriterion("\"post_content\" is not null");
            return (Criteria) this;
        }

        public Criteria andPostContentEqualTo(String value) {
            addCriterion("\"post_content\" =", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentNotEqualTo(String value) {
            addCriterion("\"post_content\" <>", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentGreaterThan(String value) {
            addCriterion("\"post_content\" >", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentGreaterThanOrEqualTo(String value) {
            addCriterion("\"post_content\" >=", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentLessThan(String value) {
            addCriterion("\"post_content\" <", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentLessThanOrEqualTo(String value) {
            addCriterion("\"post_content\" <=", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentLike(String value) {
            addCriterion("\"post_content\" like", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentNotLike(String value) {
            addCriterion("\"post_content\" not like", value, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentIn(List<String> values) {
            addCriterion("\"post_content\" in", values, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentNotIn(List<String> values) {
            addCriterion("\"post_content\" not in", values, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentBetween(String value1, String value2) {
            addCriterion("\"post_content\" between", value1, value2, "postContent");
            return (Criteria) this;
        }

        public Criteria andPostContentNotBetween(String value1, String value2) {
            addCriterion("\"post_content\" not between", value1, value2, "postContent");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("\"created_date\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("\"created_date\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("\"created_date\" =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("\"created_date\" <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("\"created_date\" >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"created_date\" >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("\"created_date\" <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("\"created_date\" <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("\"created_date\" in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("\"created_date\" not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("\"created_date\" between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("\"created_date\" not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("\"updated_date\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("\"updated_date\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("\"updated_date\" =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("\"updated_date\" <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("\"updated_date\" >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"updated_date\" >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("\"updated_date\" <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("\"updated_date\" <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("\"updated_date\" in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("\"updated_date\" not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("\"updated_date\" between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("\"updated_date\" not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("\"content_type\" is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("\"content_type\" is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(Integer value) {
            addCriterion("\"content_type\" =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(Integer value) {
            addCriterion("\"content_type\" <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(Integer value) {
            addCriterion("\"content_type\" >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"content_type\" >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(Integer value) {
            addCriterion("\"content_type\" <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(Integer value) {
            addCriterion("\"content_type\" <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<Integer> values) {
            addCriterion("\"content_type\" in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<Integer> values) {
            addCriterion("\"content_type\" not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(Integer value1, Integer value2) {
            addCriterion("\"content_type\" between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("\"content_type\" not between", value1, value2, "contentType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 11 15:38:28 MMT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table post
     *
     * @mbg.generated Fri Aug 11 15:38:28 MMT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}